custom:
  maintenance.enabled: true
  max_session_duration: 900
  session:
    wait_timeout: 60
    polling_timeout: 300
  grid:
    download_url: https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
  cron:
    reap_long_running_sessions: '*/30 * * * * ?'
    reap_unreachable_slaves: '*/30 * * * * ?'
    check_grid_service: '*/15 * * * * ?'

queue:
  name: devices
server:
  compression:
    enabled: true
  error:
    include-stacktrace: never
  port: 5252
  servlet:
    context-path: /
  tomcat:
    connection-timeout: 1800000
slave:
  auth_token: bW9iaWxlIGRldmljZSBsYWIgYXV0aCB0b2tlbg==
  port: 5353
spring:
  data:
    mongodb:
      url: mongodb://${MONGODB_HOST:localhost}:27017/device_lab
  security:
    user:
      name: user
      password: user
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH_CLIENT_ID}
            clientSecret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope:
            - email
            - profile